name: IronNetworkKT
version: '${project.version}'
main: com.envyus.ironnetworkkt.IronNetworkKT
api-version: '1.20'
commands:
  teleport:
    description: Teleport
    usage: /<command>
  diamantes:
    description: ganha diamante
    usage: /<command> (quantity)
